### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jisungbin** [carrot-style/carrot-android#2]
### TODO
- [x] 파일 없을 때 sha 구하려고 하면 `{"message":"Not Found"}` 오류 뜨는거 예외 처리
- [x] `StyledUrl` 리스트에 추가 후 `ModalBottomSheet` 닫아야 함
- [x] `StyledUrl` 리스트에 추가 돼도, `_styledUrls` 가 업데이트 되지 않음 -> 모든 컴포넌트에서 `vm` 같은 인스턴스인지 확인 필요
- [x] `StyledUrl` 업데이트 정상 작동 확인
- [x] 앱 최초 실행시 `서비스 이용약관` 다이얼로그 띄우기

**Comment by jisungbin** [comment]
다 했 다!
